# http://gitpod.io/#github.com/gnolang/gno

tasks:
  - name: Dev Shell
    init: >
      echo "install developer tools" &&
      (cd misc/devdeps && make install) &&
      echo "download dependencies" &&
      go mod download &&
      go install ./gnovm/cmd/gno
    command: gno --help

  - name: Gnoland Node
    init: go install ./gno.land/cmd/gnoland
    command: >
      cd ./gno.land &&
      gnoland start

  - name: Gnoland Website
    init: go install ./gno.land/cmd/gnoweb
    command: gnoweb --bind=0.0.0.0:8888

ports:
  - name: gnoweb
    description: "the Gno.land web server"
    port: 8888
    onOpen: open-preview
    public: true

  - name: "gnoland RPC"
    description: "the RPC server, managed by tendermint2"
    port: 36657
    onOpen: notify
    public: true
