# http://gitpod.io/#github.com/gnolang/gno

tasks:
  - name: Gno Shell
    init: |
      echo "install developer tools"
      (cd misc/devdeps && make install)
      echo "download dependencies"
      go mod download
      go install ./gnovm/cmd/gno
    command: gno --help

  - name: Gnoland Node
    before: cd ./gno.land
    init: go install ./cmd/gnoland
    command: gnoland start

  - name: Gnoland Website
    before: cd ./gno.land
    init: go install ./cmd/gnoweb
    command: gnoweb --bind=0.0.0.0:8888

  #- name: faucet
  #  ...

ports:
  - name: gnoweb
    description: "the Gno.land web server"
    port: 8888
    onOpen: open-preview
    #public: true

  - name: "gnoland RPC"
    description: "the RPC server, managed by tendermint2"
    port: 36657
    onOpen: notify
    #public: true

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: false
