name: docker
on:
  pull_request:
    paths:
      - "**"
      - "!misc/**"
      - "!docs/**"
      - "!**.md"
  push:
    branches: [ "patch/gnochess" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build main Docker image
        env:
          owner: ${{ github.repository_owner }}
          reponame: ${{ github.event.repository.name }}
        run: |
          docker build -t ghcr.io/${owner}/${reponame}/gnochess .
          docker tag ghcr.io/${owner}/${reponame}/gnochess:latest ghcr.io/${owner}/${reponame}/gnochess:${GITHUB_SHA::8}

      - name: List docker images
        run: |
          docker images | grep ghcr

      - name: Log in to GitHub Container Registry
        if: (github.event_name != 'pull_request')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish images
        if: (github.event_name != 'pull_request')
        env:
          owner: ${{ github.repository_owner }}
          reponame: ${{ github.event.repository.name }}
        run: |
            docker push ghcr.io/${owner}/${reponame}/gnochess:latest
            docker push ghcr.io/${owner}/${reponame}/gnochess:${GITHUB_SHA::8}
