name: Build and push image for GnoFee experimental

on:
  push:
    branches:
      - "feat/gno-fee-experimental"

permissions:
  contents: read
  packages: write

jobs:
  dagger-build:
    name: dagger-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Run Gnoland
        uses: dagger/dagger-for-github@v7
        with:
          version: "v0.16.1"
          verb: call
          module: misc/gno-fee/dagger
          args: build-and-run --source .

  build-push:
    needs: dagger-build
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/gnoland
          tags: |
            type=schedule
            type=raw,value=gno-fee-experimental
            type=ref,event=branch
            type=sha,prefix=sha-
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          target: gnoland
          platforms: linux/amd64 #,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
